services:
  ytgrid:
    build: .
    container_name: ytgrid_cli
    stdin_open: true  # Allow interactive CLI
    tty: true  # Keep terminal open for CLI commands
    volumes:
      - .:/app
    environment:
      - YTGRID_HEADLESS_MODE=True
      - YTGRID_DEFAULT_SPEED=1.0
      - YTGRID_DEFAULT_LOOP_COUNT=1
      - YTGRID_MAX_SESSIONS=5
      - YTGRID_REALTIME_UPDATES=False
      - YTGRID_WEBSOCKET_SERVER_URL=ws://web:8000/ws
      - YTGRID_USE_TEMP_USER_DATA=True
      - YTGRID_BROWSER_TIMEOUT=20
      - YTGRID_USE_CELERY=False  # Celery is off by default
    entrypoint: ["/bin/sh"]  # Start container with a shell for manual execution
